spring:
  application:
    name: java-pro-spring
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql
